backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: content/projects
    format: frontmatter
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: Date,
          name: date,
          widget: datetime,
          timeFormat: false,
          format: YYYY-MM-DD,
          picker_utc: true,
        }
      - { label: Description, name: description, widget: string }
      - label: Skills
        name: skills
        widget: relation
        collection: content
        file: skills
        search_fields: ["skills.*.name"]
        display_fields: ["skills.*.name"]
        value_field: "skills.*.name"
        multiple: true
        required: false
      - { label: Component, name: component, widget: string, required: false }
      - { label: Body, name: body, widget: markdown, required: false }

  - name: resume
    label: Resume
    files:
      - name: info
        label: Info
        file: content/resume/info.md
        format: frontmatter
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Job Title, name: jobTitle, widget: string }
          - {
              label: Encrypted Email Address,
              name: encryptedEmail,
              widget: string,
            }
          - {
              label: Encrypted Phone Number,
              name: encryptedPhone,
              widget: string,
            }
      - name: intro
        label: Intro
        file: content/resume/intro.md
        format: frontmatter
        fields:
          - { label: Body, name: body, widget: markdown }
      - name: education
        label: Education
        file: content/resume/education.md
        format: frontmatter
        fields:
          - name: education
            label: Education
            widget: list
            fields:
              - { label: Degree, name: degree, widget: string }
              - { label: Institution, name: institution, widget: string }
              - {
                  label: Date,
                  name: date,
                  widget: datetime,
                  timeFormat: false,
                  format: YYYY-MM-DD,
                  picker_utc: true,
                }
              - { label: Description, name: body, widget: markdown }
      - name: work
        label: Work
        file: content/resume/work.md
        format: frontmatter
        fields:
          - name: work
            label: Work
            widget: list
            fields:
              - { label: Job Title, name: title, widget: string }
              - {
                  label: Company Name,
                  name: company,
                  widget: string,
                  required: false,
                }
              - {
                  label: From,
                  name: from,
                  widget: datetime,
                  timeFormat: false,
                  format: YYYY-MM-DD,
                  picker_utc: true,
                }
              - {
                  label: To,
                  name: to,
                  widget: datetime,
                  timeFormat: false,
                  format: YYYY-MM-DD,
                  picker_utc: true,
                  required: false,
                }
              - {
                  label: Current,
                  name: current,
                  widget: boolean,
                  required: false,
                }
              - {
                  label: "Description",
                  name: body,
                  widget: markdown,
                  required: false,
                }
      - name: awards
        label: Awards
        file: content/resume/awards.md
        format: frontmatter
        fields:
          - name: awards
            label: Awards
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Organization, name: organization, widget: string }
              - {
                  label: Date,
                  name: date,
                  widget: datetime,
                  timeFormat: false,
                  format: YYYY-MM-DD,
                  picker_utc: true,
                }
              - { label: Description, name: body, widget: markdown }
      - name: service
        label: Service
        file: content/resume/service.md
        format: frontmatter
        fields:
          - name: service
            label: Service
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - {
                  label: Organization,
                  name: organization,
                  widget: string,
                  required: false,
                }
              - {
                  label: From,
                  name: from,
                  widget: datetime,
                  timeFormat: false,
                  format: YYYY-MM-DD,
                  picker_utc: true,
                }
              - {
                  label: To,
                  name: to,
                  widget: datetime,
                  timeFormat: false,
                  format: YYYY-MM-DD,
                  picker_utc: true,
                  required: false,
                }
              - { label: Description, name: body, widget: markdown }
      - name: references
        label: References
        file: content/resume/references.md
        format: frontmatter
        fields:
          - name: references
            label: References
            widget: list
            fields:
              - { label: Encrypted Name, name: encryptedName, widget: string }
              - {
                  label: Encrypted Position,
                  name: encryptedPosition,
                  widget: string,
                }
              - {
                  label: Encrypted Organization,
                  name: encryptedOrganization,
                  widget: string,
                }
              - {
                  label: Encrypted Contact,
                  name: encryptedContact,
                  widget: string,
                }
              - {
                  label: Encrypted Description,
                  name: encryptedDescription,
                  widget: string,
                }

  - label: Static Content
    name: content
    files:
      - label: Home Content
        name: homeContent
        file: content/homeContent.md
        format: frontmatter
        fields:
          - { label: Body, name: body, widget: markdown }

      - label: Skills
        name: skills
        file: content/skills.md
        format: frontmatter
        create: true
        fields:
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Icon, name: icon, widget: image, required: false }
              - label: Proficiency
                name: proficiency
                widget: select
                options:
                  - { label: "Low", value: 1 }
                  - { label: "Medium", value: 2 }
                  - { label: "High", value: 3 }
                default: { label: "High", value: 3 }
