backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: projects
    label: Projects
    folder: content/projects
    format: frontmatter
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: Component, name: component, widget: string }
      - label: Skills
        name: skills
        widget: relation
        collection: content
        file: skills
        search_fields: ["skills.*.skill"]
        display_fields: ["skills.*.skill"]

  - name: resume
    label: Resume
    files:
      - name: info
        label: Info
        file: content/resume/info.md
        format: frontmatter
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Job Title, name: jobTitle, widget: string }
          - {
              label: AES Encrypted Email Address,
              name: encryptedEmail,
              widget: string,
            }
          - {
              label: AES Encrypted Phone Number,
              name: encryptedPhone,
              widget: string,
            }
      - name: intro
        label: Intro
        file: content/resume/intro.md
        format: frontmatter
        fields:
          - { label: Body, name: body, widget: markdown }
      - name: education
        label: Education
        file: content/resume/education.md
        format: frontmatter
        fields:
          - name: education
            label: Education
            widget: list
            fields:
              - { label: Degree, name: degree, widget: string }
              - { label: Institution, name: institution, widget: string }
              - { label: Date, name: date, widget: datetime }
              - { label: Description, name: body, widget: markdown }
      - name: work
        label: Work
        file: content/resume/work.md
        format: frontmatter
        fields:
          - name: work
            label: Work
            widget: list
            fields:
              - { label: Job Title, name: title, widget: string }
              - { label: Company Name, name: company, widget: string }
              - { label: From, name: from, widget: datetime }
              - { label: To, name: to, widget: datetime }
              - { label: "Description", name: body, widget: markdown }

  - label: Static Content
    name: content
    files:
      - label: Home Content
        name: homeContent
        file: content/homeContent.md
        format: frontmatter
        fields:
          - { label: Body, name: body, widget: markdown }

      - label: Skills
        name: skills
        file: content/skills.md
        format: frontmatter
        create: true
        fields:
          - label: Skills
            name: skills
            widget: list
            fields:
              - { label: Skill, name: skill, widget: string }
              - { label: Icon, name: icon, widget: image }
              - {
                  label: Strength,
                  name: strength,
                  widget: select,
                  options: ["low", "medium", "high"],
                  default: ["high"],
                }
      # - label: Projects
      #   name: projects
      #   file: content/projects.md
      #   format: frontmatter
      #   fields:
      #     - label: Projects
      #       name: projects
      #       widget: list
      #       fields:
      #         - { label: Project Name, name: name, widget: string }
